//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRecords.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int EmployeeID { get; set; }
        public string GivenName { get; set; }
        public string Surname { get; set; }
        public string PersonalNo { get; set; }
        public string RegistrationNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Sex { get; set; }
        public string Telephone { get; set; }
        public int LocationID { get; set; }
        public string Manager { get; set; }
        public int SectorID { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblSector tblSector { get; set; }
    }
}
