//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRecords.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public string Employee_Given_Name { get; set; }
        public string Employee_Surname { get; set; }
        public string Sex { get; set; }
        public string Telephone { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Manager { get; set; }
        public int EmployeeID { get; set; }
        public string Registration_Number { get; set; }
        public int SectorID { get; set; }
        public string Sector { get; set; }
        public int LocationID { get; set; }
        public string Address { get; set; }
    }
}
